import { useState } from "react";
import { ExternalLink, RefreshCw } from "lucide-react";
import { learningApi } from "../../api/studentApi";
import { KeyValue, KeyValueGrid, SectionCard } from "../../components/ui/blocks";
import { EmptyState, ErrorState, LoadingState, ProgressBar, StatusBadge } from "../../components/ui/primitives";
import { useAction, useAsync } from "../../hooks/useAsync";
import { useToast } from "../../context/ToastContext";
import { formatHours, humanize } from "../../utils/format";
import type { LearningStatus } from "../../types";

const STATUS_OPTIONS: LearningStatus[] = ["not_started", "in_progress", "completed"];

export function LearningPathPage() {
  const toast = useToast();
  const [reloadKey, setReloadKey] = useState("0");
  const path = useAsync(() => learningApi.path(), reloadKey);
  const action = useAction();

  function done(message: string) {
    toast.success(message);
    setReloadKey(String(Date.now()));
  }

  async function refreshPath() {
    const ok = await action.run(async () => {
      await learningApi.refresh();
      return "refreshed";
    });
    if (ok) done("Learning path regenerated from your current skill gap");
  }

  async function update(itemId: number, payload: { status?: LearningStatus; progress_percent?: number }) {
    const ok = await action.run(async () => {
      await learningApi.updateItem(itemId, payload);
      return "saved";
    });
    if (ok) done("Progress saved. Completed topics feed your readiness score.");
  }

  if (path.loading) return <LoadingState label="Building your learning path…" />;
  if (path.error) return <ErrorState message={path.error} onRetry={path.reload} />;
  const data = path.data;
  if (!data) return <EmptyState title="Learning path unavailable" />;

  return (
    <div className="page-grid">
      <SectionCard
        actions={
          <button className="btn btn-outline btn-sm" disabled={action.pending} onClick={refreshPath} type="button">
            <RefreshCw size={15} /> Refresh
          </button>
        }
        eyebrow="Learning path"
        title={`${data.completed}/${data.total_items} topics complete · ${data.completion_percent}%`}
      >
        <KeyValueGrid>
          <KeyValue label="Target role" value={data.target_role ?? "Not selected"} />
          <KeyValue label="In progress" value={data.in_progress} />
          <KeyValue label="Not started" value={data.not_started} />
          <KeyValue label="Remaining effort" value={formatHours(data.remaining_estimated_hours)} />
        </KeyValueGrid>
        <div className="gap-coverage">
          <ProgressBar value={data.completion_percent} />
        </div>
        {data.next_action && (
          <div className="suggestion-box">
            <p className="eyebrow">Next recommended action</p>
            <p>{data.next_action}</p>
          </div>
        )}
        {action.error && <p className="form-error">{action.error}</p>}
        <p className="muted small">
          Generated by rule based logic from your skill gap and the curated resource catalogue. No external AI service
          is used.
        </p>
      </SectionCard>

      {data.items.length === 0 && (
        <SectionCard>
          <EmptyState
            description="Select a target role and record your skills, then refresh the path."
            title="No recommendations yet"
          />
        </SectionCard>
      )}

      <div className="roadmap">
        {data.items.map((item, index) => (
          <article className={item.status === "completed" ? "roadmap-item done" : "roadmap-item"} key={item.id}>
            <div className="roadmap-marker">{item.status === "completed" ? "✓" : index + 1}</div>
            <div className="roadmap-body">
              <div className="roadmap-head">
                <div>
                  <p className="eyebrow">
                    {item.skill_name} · {item.difficulty} · {formatHours(item.estimated_hours)}
                  </p>
                  <h4>{item.title}</h4>
                  <p className="muted small">{item.provider ?? "Curated resource"}</p>
                </div>
                <div className="roadmap-badges">
                  <StatusBadge
                    tone={item.priority === "high" ? "danger" : item.priority === "medium" ? "warning" : "neutral"}
                    value={`${item.priority} priority`}
                  />
                  <StatusBadge value={item.status} />
                </div>
              </div>

              <ProgressBar tone={item.status === "completed" ? "accent" : "gold"} value={item.progress_percent} />

              <div className="roadmap-actions">
                <label className="inline-label">
                  Status
                  <select
                    disabled={action.pending}
                    onChange={(event) => void update(item.id, { status: event.target.value as LearningStatus })}
                    value={item.status}
                  >
                    {STATUS_OPTIONS.map((option) => (
                      <option key={option} value={option}>
                        {humanize(option)}
                      </option>
                    ))}
                  </select>
                </label>
                <label className="inline-label">
                  Progress {item.progress_percent}%
                  <input
                    disabled={action.pending}
                    max={100}
                    min={0}
                    onChange={(event) => void update(item.id, { progress_percent: Number(event.target.value) })}
                    step={10}
                    type="range"
                    value={item.progress_percent}
                  />
                </label>
                {item.url && (
                  <a className="btn btn-ghost btn-sm" href={item.url} rel="noreferrer" target="_blank">
                    <ExternalLink size={14} /> Resource
                  </a>
                )}
              </div>
            </div>
          </article>
        ))}
      </div>
    </div>
  );
}
