import type { ReactNode } from "react";
import { adminApi } from "../../api/adminApi";
import { SectionCard, KeyValue, KeyValueGrid } from "../../components/ui/blocks";
import { EmptyState, ErrorState, LoadingState, StatusBadge } from "../../components/ui/primitives";
import { useAsync } from "../../hooks/useAsync";
import { formatDateTime } from "../../utils/format";

function State<T>({ data, loading, error, render }: { data: T | undefined; loading: boolean; error: string | null; render: (value: T) => ReactNode }) { if (loading) return <LoadingState />; if (error || !data) return <ErrorState message={error ?? "Data unavailable"} />; return <>{render(data)}</>; }
export function AdminDashboardPage() { const q = useAsync(adminApi.dashboard); return <State {...q} render={(d) => <div className="page-grid"><SectionCard eyebrow="Administration" title="Platform overview"><KeyValueGrid><KeyValue label="Students" value={d.counts.students} /><KeyValue label="Mentors" value={d.counts.mentors} /><KeyValue label="Open drives" value={d.counts.open_drives} /><KeyValue label="Applications" value={d.counts.applications} /><KeyValue label="Unread notifications" value={d.counts.notifications_unread} /></KeyValueGrid></SectionCard><SectionCard title="Upcoming deadlines">{d.upcoming_deadlines.map((row) => <p key={row.drive_id}>{row.drive_name} · {row.application_deadline ?? "No deadline"}</p>)}</SectionCard></div>} />; }
export function AdminUsersPage() { const q = useAsync(adminApi.users); return <State {...q} render={(d) => <List title="User management" rows={d.items.map((u) => <><strong>{u.full_name}</strong><p>{u.email} · {u.role} · <StatusBadge value={u.is_active ? "active" : "inactive"} /></p></>)} />} />; }
export function AdminStudentsPage() { const q = useAsync(adminApi.students); return <State {...q} render={(d) => <List title="Student monitoring" rows={d.map((s) => <><strong>{s.full_name}</strong><p>{s.target_role ?? "No role"} · readiness {s.overall_score ?? "—"} · mentors {s.mentor_names.join(", ") || "Unassigned"}</p></>)} />} />; }
export function AdminAssignmentsPage() { const q = useAsync(adminApi.assignments); return <State {...q} render={(d) => <List title="Mentor assignments" rows={d.map((a) => <><strong>{a.student_name}</strong><p>{a.mentor_name ?? "No mentor"} · <StatusBadge value={a.is_active ? "active" : "inactive"} /></p></>)} />} />; }
export function AdminCompaniesPage() { const q = useAsync(adminApi.companies); return <State {...q} render={(d) => <List title="Companies" rows={d.map((c) => <><strong>{c.name}</strong><p>{c.industry ?? "—"} · <StatusBadge value={c.status} /></p></>)} />} />; }
export function AdminJobsPage() { const q = useAsync(adminApi.jobs); return <State {...q} render={(d) => <List title="Job postings" rows={d.map((j) => <><strong>{j.title}</strong><p>{j.company_name ?? "—"} · <StatusBadge value={j.status} /></p></>)} />} />; }
export function AdminDrivesPage() { const q = useAsync(adminApi.drives); return <State {...q} render={(d) => <List title="Placement drives" rows={d.map((r) => <><strong>{r.name}</strong><p>{r.company_name ?? "—"} · <StatusBadge value={r.status} /></p></>)} />} />; }
export function AdminApplicationsPage() { const q = useAsync(adminApi.applications); return <State {...q} render={(d) => <List title="Application monitoring" rows={d.items.map((a) => <><strong>{a.code}</strong><p>{a.student_name ?? "Student"} · {a.drive_name ?? "Drive"} · <StatusBadge value={a.status} /></p></>)} />} />; }
export function AdminAuditPage() { const q = useAsync(adminApi.auditLogs); return <State {...q} render={(d) => <List title="Audit log" rows={d.items.map((row) => <><strong>{row.action}</strong><p>{row.actor_email ?? "System"} · {row.summary ?? row.entity_type} · {formatDateTime(row.created_at)}</p></>)} />} />; }
function List({ title, rows }: { title: string; rows: ReactNode[] }) { return <SectionCard title={title}>{rows.length ? <div className="page-grid">{rows.map((row, i) => <article className="card" key={i}>{row}</article>)}</div> : <EmptyState title="No records found" />}</SectionCard>; }
